# Uncomment if live
baseurl: /portfolio/
# Uncomment if doing local edits 
# baseurl: /

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
